-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 16:49:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prueba_intuito
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prueba_intuito` ;

-- -----------------------------------------------------
-- Schema prueba_intuito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba_intuito` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `prueba_intuito` ;

-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_asiento` (
  `id_asiento` INT NOT NULL,
  `Number` INT NULL DEFAULT NULL,
  `RowNumber` INT NULL DEFAULT NULL,
  `id_sala` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_asiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_cartelera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_cartelera` (
  `idBillboardEntity` INT NOT NULL,
  `Date` DATETIME NULL DEFAULT NULL,
  `Start_Time` TIMESTAMP(6) NULL DEFAULT NULL,
  `End_Time` TIMESTAMP(6) NULL DEFAULT NULL,
  `id_pelicula` INT NULL DEFAULT NULL,
  `id_sala` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idBillboardEntity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_cliente` (
  `id_cliente` INT NOT NULL,
  `Cedula` INT NULL DEFAULT NULL,
  `Nombres` VARCHAR(45) NULL DEFAULT NULL,
  `Apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `Edad` INT NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Correo_electronico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_pelicula` (
  `id_pelicula` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Genero` VARCHAR(45) NULL DEFAULT NULL,
  `Edad_permitida` INT NULL DEFAULT NULL,
  `Duracion` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pelicula`),
  CONSTRAINT `fk_entidad_pelicula_entidad_cartelera1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `prueba_intuito`.`entidad_cartelera` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_reserva` (
  `id_reserva` INT NOT NULL,
  `Date` DATETIME NULL DEFAULT NULL,
  `id_cliente` INT NOT NULL,
  `id_cartelera` INT NOT NULL,
  `id_asiento` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  CONSTRAINT `fk_entidad_reserva_entidad_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `prueba_intuito`.`entidad_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_reserva_entidad_cartelera1`
    FOREIGN KEY (`id_cartelera`)
    REFERENCES `prueba_intuito`.`entidad_cartelera` (`idBillboardEntity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_reserva_entidad_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `prueba_intuito`.`entidad_asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_entidad_reserva_entidad_cliente1_idx` ON `prueba_intuito`.`entidad_reserva` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_entidad_reserva_entidad_cartelera1_idx` ON `prueba_intuito`.`entidad_reserva` (`id_cartelera` ASC) VISIBLE;

CREATE INDEX `fk_entidad_reserva_entidad_asiento1_idx` ON `prueba_intuito`.`entidad_reserva` (`id_asiento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_sala` (
  `id_sala` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_sala`),
  CONSTRAINT `fk_entidad_sala_entidad_cartelera1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `prueba_intuito`.`entidad_cartelera` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prueba_intuito`.`entidad_sala_has_entidad_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_intuito`.`entidad_sala_has_entidad_asiento` (
  `entidad_sala_id_sala` INT NOT NULL,
  `entidad_asiento_id_asiento` INT NOT NULL,
  PRIMARY KEY (`entidad_sala_id_sala`, `entidad_asiento_id_asiento`),
  CONSTRAINT `fk_entidad_sala_has_entidad_asiento_entidad_sala1`
    FOREIGN KEY (`entidad_sala_id_sala`)
    REFERENCES `prueba_intuito`.`entidad_sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_sala_has_entidad_asiento_entidad_asiento1`
    FOREIGN KEY (`entidad_asiento_id_asiento`)
    REFERENCES `prueba_intuito`.`entidad_asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_entidad_sala_has_entidad_asiento_entidad_asiento1_idx` ON `prueba_intuito`.`entidad_sala_has_entidad_asiento` (`entidad_asiento_id_asiento` ASC) VISIBLE;

CREATE INDEX `fk_entidad_sala_has_entidad_asiento_entidad_sala1_idx` ON `prueba_intuito`.`entidad_sala_has_entidad_asiento` (`entidad_sala_id_sala` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
